// AUTO-GENERATED by scripts/i18n/gen-blog-index.mjs — do not edit by hand.
// Edge runtime fs okuyamaz, bu yuzden build-time static import gerekiyor.
// Yeni blog JSON ekleyince: node scripts/i18n/gen-blog-index.mjs
//
// Importers: src/app/[locale]/blog/[slug]/page.tsx, sitemap.ts, blog/page.tsx, blog/rss.xml/route.ts

import a_de_best_time_cappadocia_balloon from "./de-best-time-cappadocia-balloon.json";
import a_de_cappadocia_winter_2026_guide from "./de-cappadocia-winter-2026-guide.json";
import a_de_heissluftballon_kappadokien_preise from "./de-heissluftballon-kappadokien-preise.json";
import a_de_kapadokya_aktiviteler from "./de-kapadokya-aktiviteler.json";
import a_de_kapadokya_dugun_fotografciligi from "./de-kapadokya-dugun-fotografciligi.json";
import a_de_kapadokya_fotograf_noktalari from "./de-kapadokya-fotograf-noktalari.json";
import a_de_kapadokya_istanbuldan_nasil_gidilir from "./de-kapadokya-istanbuldan-nasil-gidilir.json";
import a_de_kapadokya_ne_zaman_gidilir from "./de-kapadokya-ne-zaman-gidilir.json";
import a_de_kapadokya_otel_tavsiye_2026 from "./de-kapadokya-otel-tavsiye-2026.json";
import a_en_best_time_cappadocia_balloon from "./en-best-time-cappadocia-balloon.json";
import a_en_cappadocia_hot_air_balloon_price_2026 from "./en-cappadocia-hot-air-balloon-price-2026.json";
import a_en_cappadocia_winter_2026_guide from "./en-cappadocia-winter-2026-guide.json";
import a_en_heissluftballon_kappadokien_preise from "./en-heissluftballon-kappadokien-preise.json";
import a_en_kapadokya_aktiviteler from "./en-kapadokya-aktiviteler.json";
import a_en_kapadokya_dugun_fotografciligi_rehberi from "./en-kapadokya-dugun-fotografciligi-rehberi.json";
import a_en_kapadokya_fotograf_noktalari from "./en-kapadokya-fotograf-noktalari.json";
import a_en_kapadokya_istanbuldan_nasil_gidilir from "./en-kapadokya-istanbuldan-nasil-gidilir.json";
import a_en_kapadokya_ne_zaman_gidilir from "./en-kapadokya-ne-zaman-gidilir.json";
import a_en_kapadokya_otel_tavsiye_2026 from "./en-kapadokya-otel-tavsiye-2026.json";
import a_es_best_time_cappadocia_balloon from "./es-best-time-cappadocia-balloon.json";
import a_es_cappadocia_winter_2026_guide from "./es-cappadocia-winter-2026-guide.json";
import a_es_heissluftballon_kappadokien_preise from "./es-heissluftballon-kappadokien-preise.json";
import a_es_kapadokya_aktiviteler from "./es-kapadokya-aktiviteler.json";
import a_es_kapadokya_dugun_fotografciligi from "./es-kapadokya-dugun-fotografciligi.json";
import a_es_kapadokya_fotograf_noktalari from "./es-kapadokya-fotograf-noktalari.json";
import a_es_kapadokya_istanbuldan_nasil_gidilir from "./es-kapadokya-istanbuldan-nasil-gidilir.json";
import a_es_kapadokya_ne_zaman_gidilir from "./es-kapadokya-ne-zaman-gidilir.json";
import a_es_kapadokya_otel_tavsiye_2026 from "./es-kapadokya-otel-tavsiye-2026.json";
import a_fr_best_time_cappadocia_balloon from "./fr-best-time-cappadocia-balloon.json";
import a_fr_cappadocia_winter_2026_guide from "./fr-cappadocia-winter-2026-guide.json";
import a_fr_heissluftballon_kappadokien_preise_buchung from "./fr-heissluftballon-kappadokien-preise-buchung.json";
import a_fr_kapadokya_aktiviteler from "./fr-kapadokya-aktiviteler.json";
import a_fr_kapadokya_dugun_fotografciligi_rehberi from "./fr-kapadokya-dugun-fotografciligi-rehberi.json";
import a_fr_kapadokya_fotograf_noktalari from "./fr-kapadokya-fotograf-noktalari.json";
import a_fr_kapadokya_istanbuldan_nasil_gidilir from "./fr-kapadokya-istanbuldan-nasil-gidilir.json";
import a_fr_kapadokya_ne_zaman_gidilir from "./fr-kapadokya-ne-zaman-gidilir.json";
import a_fr_kapadokya_otel_tavsiye_2026 from "./fr-kapadokya-otel-tavsiye-2026.json";
import a_hi_best_time_cappadocia_balloon from "./hi-best-time-cappadocia-balloon.json";
import a_hi_cappadocia_winter_2026_guide from "./hi-cappadocia-winter-2026-guide.json";
import a_hi_heissluftballon_kappadokien_preise_buchung from "./hi-heissluftballon-kappadokien-preise-buchung.json";
import a_hi_kapadokya_aktiviteler from "./hi-kapadokya-aktiviteler.json";
import a_hi_kapadokya_dugun_fotografciligi_rehberi from "./hi-kapadokya-dugun-fotografciligi-rehberi.json";
import a_hi_kapadokya_fotograf_noktalari from "./hi-kapadokya-fotograf-noktalari.json";
import a_hi_kapadokya_istanbuldan_nasil_gidilir from "./hi-kapadokya-istanbuldan-nasil-gidilir.json";
import a_hi_kapadokya_ne_zaman_gidilir from "./hi-kapadokya-ne-zaman-gidilir.json";
import a_hi_kapadokya_otel_tavsiye_2026 from "./hi-kapadokya-otel-tavsiye-2026.json";
import a_nl_best_time_cappadocia_balloon from "./nl-best-time-cappadocia-balloon.json";
import a_nl_cappadocia_winter_2026_guide from "./nl-cappadocia-winter-2026-guide.json";
import a_nl_heissluftballon_kappadokien_preise_buchung from "./nl-heissluftballon-kappadokien-preise-buchung.json";
import a_nl_kapadokya_aktiviteler from "./nl-kapadokya-aktiviteler.json";
import a_nl_kapadokya_dugun_fotografciligi from "./nl-kapadokya-dugun-fotografciligi.json";
import a_nl_kapadokya_fotograf_noktalari from "./nl-kapadokya-fotograf-noktalari.json";
import a_nl_kapadokya_istanbuldan_nasil_gidilir from "./nl-kapadokya-istanbuldan-nasil-gidilir.json";
import a_nl_kapadokya_ne_zaman_gidilir from "./nl-kapadokya-ne-zaman-gidilir.json";
import a_nl_kapadokya_otel_tavsiye_2026 from "./nl-kapadokya-otel-tavsiye-2026.json";
import a_tr_best_time_cappadocia_balloon from "./tr-best-time-cappadocia-balloon.json";
import a_tr_cappadocia_winter_2026_guide from "./tr-cappadocia-winter-2026-guide.json";
import a_tr_heissluftballon_kappadokien_preise from "./tr-heissluftballon-kappadokien-preise.json";
import a_tr_kapadokya_aktiviteler from "./tr-kapadokya-aktiviteler.json";
import a_tr_kapadokya_balon_turu_fiyat_2026 from "./tr-kapadokya-balon-turu-fiyat-2026.json";
import a_tr_kapadokya_dugun_fotografciligi from "./tr-kapadokya-dugun-fotografciligi.json";
import a_tr_kapadokya_fotograf_noktalari from "./tr-kapadokya-fotograf-noktalari.json";
import a_tr_kapadokya_istanbuldan_nasil_gidilir from "./tr-kapadokya-istanbuldan-nasil-gidilir.json";
import a_tr_kapadokya_ne_zaman_gidilir from "./tr-kapadokya-ne-zaman-gidilir.json";
import a_tr_kapadokya_otel_tavsiye_2026 from "./tr-kapadokya-otel-tavsiye-2026.json";
import a_ur_best_time_cappadocia_balloon from "./ur-best-time-cappadocia-balloon.json";
import a_ur_cappadocia_winter_2026_guide from "./ur-cappadocia-winter-2026-guide.json";
import a_ur_heissluftballon_kappadokien_preise_buchung from "./ur-heissluftballon-kappadokien-preise-buchung.json";
import a_ur_kapadokya_aktiviteler from "./ur-kapadokya-aktiviteler.json";
import a_ur_kapadokya_dugun_fotografciligi_rehberi from "./ur-kapadokya-dugun-fotografciligi-rehberi.json";
import a_ur_kapadokya_fotograf_noktalari from "./ur-kapadokya-fotograf-noktalari.json";
import a_ur_kapadokya_istanbuldan_nasil_gidilir from "./ur-kapadokya-istanbuldan-nasil-gidilir.json";
import a_ur_kapadokya_ne_zaman_gidilir from "./ur-kapadokya-ne-zaman-gidilir.json";
import a_ur_kapadokya_otel_tavsiye_2026 from "./ur-kapadokya-otel-tavsiye-2026.json";
import a_zh_best_time_cappadocia_balloon from "./zh-best-time-cappadocia-balloon.json";
import a_zh_cappadocia_winter_2026_guide from "./zh-cappadocia-winter-2026-guide.json";
import a_zh_heissluftballon_kappadokien_preise_buchung from "./zh-heissluftballon-kappadokien-preise-buchung.json";
import a_zh_kapadokya_aktiviteler from "./zh-kapadokya-aktiviteler.json";
import a_zh_kapadokya_dugun_fotografciligi from "./zh-kapadokya-dugun-fotografciligi.json";
import a_zh_kapadokya_fotograf_noktalari from "./zh-kapadokya-fotograf-noktalari.json";
import a_zh_kapadokya_istanbuldan_nasil_gidilir from "./zh-kapadokya-istanbuldan-nasil-gidilir.json";
import a_zh_kapadokya_ne_zaman_gidilir from "./zh-kapadokya-ne-zaman-gidilir.json";
import a_zh_kapadokya_otel_tavsiye_2026 from "./zh-kapadokya-otel-tavsiye-2026.json";

export interface BlogArticle {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  excerpt: string;
  content: string;
  category: string;
  tags: string[];
  targetKeyword: string;
  locale: string;
  publishedAt: string;
  seoScore: number;
  isAiGenerated?: boolean;
  /** Relative path under /public — e.g. "/images/blog/<slug>.jpg". */
  coverImage?: string;
  faq?: { question: string; answer: string }[];
}

export const ARTICLES: BlogArticle[] = [
  a_de_best_time_cappadocia_balloon as BlogArticle,
  a_de_cappadocia_winter_2026_guide as BlogArticle,
  a_de_heissluftballon_kappadokien_preise as BlogArticle,
  a_de_kapadokya_aktiviteler as BlogArticle,
  a_de_kapadokya_dugun_fotografciligi as BlogArticle,
  a_de_kapadokya_fotograf_noktalari as BlogArticle,
  a_de_kapadokya_istanbuldan_nasil_gidilir as BlogArticle,
  a_de_kapadokya_ne_zaman_gidilir as BlogArticle,
  a_de_kapadokya_otel_tavsiye_2026 as BlogArticle,
  a_en_best_time_cappadocia_balloon as BlogArticle,
  a_en_cappadocia_hot_air_balloon_price_2026 as BlogArticle,
  a_en_cappadocia_winter_2026_guide as BlogArticle,
  a_en_heissluftballon_kappadokien_preise as BlogArticle,
  a_en_kapadokya_aktiviteler as BlogArticle,
  a_en_kapadokya_dugun_fotografciligi_rehberi as BlogArticle,
  a_en_kapadokya_fotograf_noktalari as BlogArticle,
  a_en_kapadokya_istanbuldan_nasil_gidilir as BlogArticle,
  a_en_kapadokya_ne_zaman_gidilir as BlogArticle,
  a_en_kapadokya_otel_tavsiye_2026 as BlogArticle,
  a_es_best_time_cappadocia_balloon as BlogArticle,
  a_es_cappadocia_winter_2026_guide as BlogArticle,
  a_es_heissluftballon_kappadokien_preise as BlogArticle,
  a_es_kapadokya_aktiviteler as BlogArticle,
  a_es_kapadokya_dugun_fotografciligi as BlogArticle,
  a_es_kapadokya_fotograf_noktalari as BlogArticle,
  a_es_kapadokya_istanbuldan_nasil_gidilir as BlogArticle,
  a_es_kapadokya_ne_zaman_gidilir as BlogArticle,
  a_es_kapadokya_otel_tavsiye_2026 as BlogArticle,
  a_fr_best_time_cappadocia_balloon as BlogArticle,
  a_fr_cappadocia_winter_2026_guide as BlogArticle,
  a_fr_heissluftballon_kappadokien_preise_buchung as BlogArticle,
  a_fr_kapadokya_aktiviteler as BlogArticle,
  a_fr_kapadokya_dugun_fotografciligi_rehberi as BlogArticle,
  a_fr_kapadokya_fotograf_noktalari as BlogArticle,
  a_fr_kapadokya_istanbuldan_nasil_gidilir as BlogArticle,
  a_fr_kapadokya_ne_zaman_gidilir as BlogArticle,
  a_fr_kapadokya_otel_tavsiye_2026 as BlogArticle,
  a_hi_best_time_cappadocia_balloon as BlogArticle,
  a_hi_cappadocia_winter_2026_guide as BlogArticle,
  a_hi_heissluftballon_kappadokien_preise_buchung as BlogArticle,
  a_hi_kapadokya_aktiviteler as BlogArticle,
  a_hi_kapadokya_dugun_fotografciligi_rehberi as BlogArticle,
  a_hi_kapadokya_fotograf_noktalari as BlogArticle,
  a_hi_kapadokya_istanbuldan_nasil_gidilir as BlogArticle,
  a_hi_kapadokya_ne_zaman_gidilir as BlogArticle,
  a_hi_kapadokya_otel_tavsiye_2026 as BlogArticle,
  a_nl_best_time_cappadocia_balloon as BlogArticle,
  a_nl_cappadocia_winter_2026_guide as BlogArticle,
  a_nl_heissluftballon_kappadokien_preise_buchung as BlogArticle,
  a_nl_kapadokya_aktiviteler as BlogArticle,
  a_nl_kapadokya_dugun_fotografciligi as BlogArticle,
  a_nl_kapadokya_fotograf_noktalari as BlogArticle,
  a_nl_kapadokya_istanbuldan_nasil_gidilir as BlogArticle,
  a_nl_kapadokya_ne_zaman_gidilir as BlogArticle,
  a_nl_kapadokya_otel_tavsiye_2026 as BlogArticle,
  a_tr_best_time_cappadocia_balloon as BlogArticle,
  a_tr_cappadocia_winter_2026_guide as BlogArticle,
  a_tr_heissluftballon_kappadokien_preise as BlogArticle,
  a_tr_kapadokya_aktiviteler as BlogArticle,
  a_tr_kapadokya_balon_turu_fiyat_2026 as BlogArticle,
  a_tr_kapadokya_dugun_fotografciligi as BlogArticle,
  a_tr_kapadokya_fotograf_noktalari as BlogArticle,
  a_tr_kapadokya_istanbuldan_nasil_gidilir as BlogArticle,
  a_tr_kapadokya_ne_zaman_gidilir as BlogArticle,
  a_tr_kapadokya_otel_tavsiye_2026 as BlogArticle,
  a_ur_best_time_cappadocia_balloon as BlogArticle,
  a_ur_cappadocia_winter_2026_guide as BlogArticle,
  a_ur_heissluftballon_kappadokien_preise_buchung as BlogArticle,
  a_ur_kapadokya_aktiviteler as BlogArticle,
  a_ur_kapadokya_dugun_fotografciligi_rehberi as BlogArticle,
  a_ur_kapadokya_fotograf_noktalari as BlogArticle,
  a_ur_kapadokya_istanbuldan_nasil_gidilir as BlogArticle,
  a_ur_kapadokya_ne_zaman_gidilir as BlogArticle,
  a_ur_kapadokya_otel_tavsiye_2026 as BlogArticle,
  a_zh_best_time_cappadocia_balloon as BlogArticle,
  a_zh_cappadocia_winter_2026_guide as BlogArticle,
  a_zh_heissluftballon_kappadokien_preise_buchung as BlogArticle,
  a_zh_kapadokya_aktiviteler as BlogArticle,
  a_zh_kapadokya_dugun_fotografciligi as BlogArticle,
  a_zh_kapadokya_fotograf_noktalari as BlogArticle,
  a_zh_kapadokya_istanbuldan_nasil_gidilir as BlogArticle,
  a_zh_kapadokya_ne_zaman_gidilir as BlogArticle,
  a_zh_kapadokya_otel_tavsiye_2026 as BlogArticle,
];
